// <auto-generated />
namespace Proyecto_Supermercado.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Supermercado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Supermercado));
        
        string IMigrationMetadata.Id
        {
            get { return "201803200302165_Supermercado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
